### ISSUE TITLE
X11 access not being granted

### ISSUE THREAD

**Issue by mmstick** [flathub/com.github.Flacon#13] opened 2020-09-12 18:01 UTC
```
# flatpak --version
Flatpak 1.6.5
```

```
# flatpak list
Name                              Application ID                               Version          Branch          Installation
Flacon                            com.github.Flacon                            6.1.0            stable          user
default                           org.freedesktop.Platform.GL.default                           20.08           user
openh264                          org.freedesktop.Platform.openh264            2.1.0            2.0             user
Pop Gtk theme                     org.gtk.Gtk3theme.Pop-dark                                    3.22            user
KDE Application Platform          org.kde.Platform                                              5.15            user
```

```
# glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.35.0, 5.4.0-7642-generic, LLVM 10.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.0-devel (git-2f62a44 2020-09-10 focal-oibaf-ppa)
```

```
# flatpak --verbose run com.github.Flacon
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/mmstick/.local/share/flatpak
F: Opening user flatpak installation at path /home/mmstick/.local/share/flatpak
F: Opening user flatpak installation at path /home/mmstick/.local/share/flatpak
F: Cleaning up unused container id 372283158
F: Allocated instance id 3360236696
F: Add defaults in dir /com/github/Flacon/
F: Add locks in dir /com/github/Flacon/
F: Allowing dri access
F: Allowing wayland access
F: Running 'bwrap --args 30 xdg-dbus-proxy --args=32'
F: Running 'bwrap --args 30 flacon'
Start flacon  6.1.0
Warning: could not connect to display
Could not load the Qt platform plugin "xcb" in "" even though it was found.
Error: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

**Comment by mmstick** [comment] 2020-09-12 18:08
X11 support only works when running with

```
flatpak run --nosocket=fallback-x11 --socket=x11 com.github.Flacon
```

**Comment by Eonfge** [comment] 2020-09-13 10:12
Just double checking; You're running this on Wayland? Know that they changed support around for the fallback command, so perhaps it broke there. Also, do you use KDE or GNOME? 

I've just tested in in a VM, Fedora 33 Rawhide and Wayland, and that works.

Let me investigate

**Comment by mmstick** [comment] 2020-09-13 21:49
No, X11 on GNOME 3.36

**Comment by Eonfge** [comment] 2020-09-16 17:42
That's so weird. Perhaps I'll have to give it another shot on Pop_OS (assuming you use Pop_OS here), but I don't know why that would make a difference.

**Comment by Eonfge** [comment] 2021-04-25 18:49
I owe you a mea culpa.I totally forgot this issue... In the end, I only have so much spare time and low priority issues often fall to the wayside. As it happens, 2020 was also a bad year for buying CD's and I don't see that change any time.

But, back on topic, before I look into the  again, do you still have this issue?

**Comment by SokoloffA** [comment] 2021-04-25 20:03
It looks like I have a related [issue](https://github.com/flacon/flacon/issues/153). If you have anything to say, I'll be happy?

**Comment by hfiguiere** [comment] 2021-04-25 20:48
For starter you shouldn't have `--socket=x11` and `--socket=fallback-x11` together.

If you allow Wayland, the latter should be used.

**Comment by hfiguiere** [comment] 2021-04-25 20:50
BTW are you trying to run this as root? You show a `#` as a prompt which makes me think this.

**Comment by Eonfge** [comment] 2021-04-26 05:57
@hfiguiere @mmstick and @Sebastian-Hirsch
I have a beta release that should now properly work on all Wayland systems. I removed the old X11 permission as well as the direct rendering permissions. This means that it should be Wayland first, with a fallback to X11 for those use that.

Can you let me know if this works:
```
flatpak install --user https://dl.flathub.org/build-repo/44424/com.github.Flacon.flatpakref
```

https://github.com/flathub/com.github.Flacon/pull/17

**Comment by ghost** [comment] 2021-04-26 07:11
This does sadly not fix the issue the same error message occurs as before.

![Bildschirmfoto von 2021-04-26 09-09-26](https://user-images.githubusercontent.com/41188546/116042922-4ab6b280-a66f-11eb-8d27-956ba27cb4ea.png)

**Comment by ghost** [comment] 2021-04-26 07:16
But I could find a workaround. I forced for all Qt-Apps on the system the xcb backend. After removing the following from my environment file, flacon starts up:

QT_QPA_PLATFORM=xcb

Interestingly, only the flacon flatpak has an issue with this.

**Comment by ghost** [comment] 2021-04-26 07:22
Running the flacon flatpak from the stable repo with QT_QPA_PLATFORM=wayland or QT_QPA_PLATFORM=wayland-egl works fine.

This is how I configured the app with flatseal. Please ignore the scale factor and dpi vars as these are specific to my system it seems that the xcb backend of qt is not available in this flatpak, or this disabled, because I use the gnome wayland session. This seems like a bug.

![Bildschirmfoto von 2021-04-26 09-33-44](https://user-images.githubusercontent.com/41188546/116045878-c6fec500-a672-11eb-83c9-6dd439cb5cde.png)

**Comment by ghost** [comment] 2021-04-26 07:40
When I launch a gnome xorg session and then start flacon with the xcb backend, it works fine. It seems that the qt xcb backend for flacon gets disabled in the wayland session. This is undesirable as the qt wayland backend is buggy with the gnome wayland session (no window shadows, resizing of window with mouse is difficult).

**Comment by hfiguiere** [comment] 2021-04-26 16:28
Why removing DRI?

**Comment by hfiguiere** [comment] 2021-04-26 16:30
> When I launch a gnome xorg session and then start flacon with the xcb backend, it works fine. It seems that the qt xcb backend for flacon gets disabled in the wayland session. This is undesirable as the qt wayland backend is buggy with the gnome wayland session (no window shadows, resizing of window with mouse is difficult).

The KDE runtime has a patch to force wayland. See https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/d2db53cd10241dee6b11a5ad097e3e61a978a14e

I am not sure if that the source of the problem, but it sure is that sometime I forced disabling wayland on Qt app to work.

**Comment by ghost** [comment] 2021-04-26 17:58
> The KDE runtime has a patch to force wayland. See https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/d2db53cd10241dee6b11a5ad097e3e61a978a14e

Very interesting! When I disable the wayland socket in flatseal and set QT_QPA_PLATFORM=xcb, it works.

**Comment by Eonfge** [comment] 2021-04-26 20:24
I rolled back some erroneous changes, but I removed the x11 socket in favour of the fallback:
```
flatpak install --user https://dl.flathub.org/build-repo/44532/com.github.Flacon.flatpakref
```

**Comment by ghost** [comment] 2021-04-26 20:33
This version does still have the same issue as the one in the stable flatpak repo. It Also still enables the x11 socket for me. But even when disabling it manually, it does not fix the startup issue for me.

![Bildschirmfoto von 2021-04-26 22-32-32](https://user-images.githubusercontent.com/41188546/116146922-593cb280-a6df-11eb-90e3-5b46d9ce0a6c.png)

**Comment by Eonfge** [comment] 2021-04-26 20:37
> It Also still enables the x11 socket for me.

It will do that for you if you run on X11... I guess that's how it just works. You can even see it in Flatseal. Honestly, I fear it's environment related. 

@Sebastian-Hirsch Can you sell me what distro you use? I think that I'll have to reproduce this with Kubuntu or similar, and even then, it sounds like something Runtime/KDE related.

**Comment by ghost** [comment] 2021-04-26 20:43
> It will do that for you if you run on X11... I guess that's how it just works. You can even see it in Flatseal. Honestly, I fear it's environment related.

But I run a gnome wayland session. It runs fine fine for me, so no X11 session here.

> Can you sell me what distro you use? I think that I'll have to reproduce this with Kubuntu or similar, and even then, it sounds like something Runtime/KDE related.

I use fedora 34 with gnome wayland as the desktop. And it is free so no need to sell you anything ;-).

**Comment by Eonfge** [comment] 2021-04-26 20:56
> It runs fine fine for me

Wait what, I was under the impression that it didn't work for you.

Comparing it with other KDE apps like Audacious, master-branch Flacon has all the same permissions. As such, I can only assume that it's something environment or package related. Forcing all KDE apps to use an alternative wayland backend could be the cause of the issue, so in that case I think it's best to not change anything for the time being.

**Comment by ghost** [comment] 2021-04-26 21:06
> Wait what, I was under the impression that it didn't work for you.

I mean the gnome session, not flacon. The flacon flatpak is still borked for me.

> so in that case I think it's best to not change anything for the time being.

The easiest way to make the xcb backend work is to just disable the wayland socket. But that breaks wayland support, so this is not a permanent solution for this problem.

**Comment by Eonfge** [comment] 2021-11-15 16:11
Hey all, 

Sorry for asking, but is this still an issue with 8.0.0? 

We updated the runtime and I hope that the issue has been resolved in the mean time. There were previously some configuration issues  but we only ever had a single reported case of this problem and I can't reproduce it in a VM running Wayland.

**Comment by Eonfge** [comment] 2022-01-18 20:34
Feel free to reopen the issue if you can help me. Otherwise, I don't really have anything to do.

**Closed as completed by Eonfge** 2022-01-18 20:34 UTC
